# Generated by Django 5.1 on 2024-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_produto_imgproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imgProduto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
